<link rel="stylesheet" href="<?= BASE_URL;?>css/normalize.css">
<link rel="stylesheet" href="<?= BASE_URL;?>css/bootstrap.min.css"/>
<link rel="stylesheet" href="<?= BASE_URL;?>css/font-awesome.min.css"/>
<link rel="stylesheet" href="<?= BASE_URL;?>css/beemuse.min.css"/>
<link rel="stylesheet" href="<?= BASE_URL;?>css/animate.css"/>
<link rel="stylesheet" href="<?= BASE_URL;?>css/entity.css">
<link href='http://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Average+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>